require 'component_host/controls/error'
require 'component_host/controls/name'
require 'component_host/controls/component_initiator'
require 'component_host/controls/component_initiator/actor_crashes'
require 'component_host/controls/component_initiator/raises_error'
require 'component_host/controls/component_initiator/runs_continuously'
require 'component_host/controls/component_initiator/stops_immediately'
